version: '2.4'

services:
  my_base_service:
    image: aws-test-image
    build:
      context: .
    container_name: aws-test-base
    volumes:
      - ${PWD}:/app
    environment:
      - AWS_ENDPOINT_URL=http://aws-local:4566
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=placeholder
      - AWS_SECRET_ACCESS_KEY=placeholder


  my-service:
    extends: my_base_service
    container_name: aws-test
    depends_on:
      - aws-local
    command: ["python", "create_topic.py"]
    

  aws-local:
    container_name: aws-local
    image: localstack/localstack:0.12.11
    environment:
      - SERVICES=sns,sqs
    ports:
      - "4566"